services:
  postgres:
    image: postgres
    container_name: tech_ai_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./tech_ai_database:/var/lib/postgresql/data
    networks:
      - tech_ai_network

volumes:
  tech_ai_database:

networks:
  tech_ai_network:
    driver: bridge
