"""initial

Revision ID: 1a64607a0b6a
Revises:
Create Date: 2024-09-21 11:42:09.222995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a64607a0b6a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vk_id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("date_of_birth", sa.String(), nullable=False),
        sa.Column("year_of_birth", sa.Integer(), nullable=True),
        sa.Column("average_likes_photos", sa.Float(), nullable=False),
        sa.Column("average_likes_posts", sa.Float(), nullable=False),
        sa.Column("interest", sa.String(), nullable=True),
        sa.Column("friends_count", sa.Integer(), nullable=False),
        sa.Column("posts_count", sa.String(), nullable=False),
        sa.Column("photo_count", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vk_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
