"""Other Tables

Revision ID: 4b27a083cb2c
Revises: 1a64607a0b6a
Create Date: 2024-09-21 12:52:47.162010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b27a083cb2c"
down_revision: Union[str, None] = "1a64607a0b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("friend_id", sa.Integer(), nullable=False),
        sa.Column("friend_city", sa.String(), nullable=True),
        sa.Column("friend_education", sa.String(), nullable=True),
        sa.Column("friend_job", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("group_description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=False),
        sa.Column("photo_count_likes", sa.Integer(), nullable=False),
        sa.Column("photo_description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_vk_id", sa.Integer(), nullable=False),
        sa.Column("post_date", sa.String(), nullable=False),
        sa.Column("post_text", sa.String(), nullable=True),
        sa.Column("post_author", sa.Integer(), nullable=False),
        sa.Column("post_friend_or_not_friend", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("photo")
    op.drop_table("groups")
    op.drop_table("friends")
    # ### end Alembic commands ###
