"""Added AI description to photos

Revision ID: bdecfedce6b7
Revises: 0feea92259a6
Create Date: 2024-09-22 13:01:07.047323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdecfedce6b7'
down_revision: Union[str, None] = '0feea92259a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('photo_description_ru', sa.String(), nullable=True))
    op.add_column('photo', sa.Column('photo_description_colors', sa.String(), nullable=True))
    op.add_column('photo', sa.Column('photo_description_category', sa.String(), nullable=True))
    op.add_column('photo', sa.Column('photo_description_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'photo_description_style')
    op.drop_column('photo', 'photo_description_category')
    op.drop_column('photo', 'photo_description_colors')
    op.drop_column('photo', 'photo_description_ru')
    # ### end Alembic commands ###
